from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FloatField, SelectField
from wtforms.validators import DataRequired, NumberRange

class MyForm(FlaskForm):
    class Meta:  # Ignoring CSRF security feature.
        csrf = False

    input_field = StringField(label='Input:', id='input_field',
                              validators=[DataRequired()],
                              render_kw={'style': 'width:50%'})

    magnitude = FloatField(
        label='Magnitude:',
        validators=[DataRequired(), NumberRange(min=-3, max=3)],
        render_kw={'style': 'width:20%', 'step': '0.1'}  # Adjust 'step' for desired increment
    )

    text_options = SelectField(label='Select Option:',
        choices= [
    ('./nlp/data/vectors/Adventurous_Cautious.pt', 'Adventurous - Cautious'),
    ('./nlp/data/vectors/Ambitious_Content.pt', 'Ambitious - Content'),
    ('./nlp/data/vectors/Analytical_Intuitive.pt', 'Analytical - Intuitive'),
    ('./nlp/data/vectors/Appreciative_Unappreciative.pt', 'Appreciative - Unappreciative'),
    ('./nlp/data/vectors/Arrogant_Humble.pt', 'Arrogant - Humble'),
    ('./nlp/data/vectors/Assertive_Passive.pt', 'Assertive - Passive'),
    ('./nlp/data/vectors/Authentic_Artificial.pt', 'Authentic - Artificial'),
    ('./nlp/data/vectors/Bold_Reserved.pt', 'Bold - Reserved'),
    ('./nlp/data/vectors/Buoyant_Desolate.pt', 'Buoyant - Desolate'),
    ('./nlp/data/vectors/Candid_Guarded.pt', 'Candid - Guarded'),
    ('./nlp/data/vectors/Casual_Formal.pt', 'Casual - Formal'),
    ('./nlp/data/vectors/Cheerful_Melancholic.pt', 'Cheerful - Melancholic'),
    ('./nlp/data/vectors/Compassionate_Cold-hearted.pt', 'Compassionate - Cold-hearted'),
    ('./nlp/data/vectors/Compelling_Unconvincing.pt', 'Compelling - Unconvincing'),
    ('./nlp/data/vectors/Concise_Lengthy.pt', 'Concise - Lengthy'),
    ('./nlp/data/vectors/Concise_Wordy.pt', 'Concise - Wordy'),
    ('./nlp/data/vectors/Confident_Insecure.pt', 'Confident - Insecure'),
    ('./nlp/data/vectors/Confident_Timid.pt', 'Confident - Timid'),
    ('./nlp/data/vectors/Considerate_Thoughtless.pt', 'Considerate - Thoughtless'),
    ('./nlp/data/vectors/Contemplative_Shallow.pt', 'Contemplative - Shallow'),
    ('./nlp/data/vectors/Cooperative_Uncooperative.pt', 'Cooperative - Uncooperative'),
    ('./nlp/data/vectors/Courageous_Timid.pt', 'Courageous - Timid'),
    ('./nlp/data/vectors/Courteous_Brusque.pt', 'Courteous - Brusque'),
    ('./nlp/data/vectors/Courteous_Rude.pt', 'Courteous - Rude'),
    ('./nlp/data/vectors/Defensive_Open.pt', 'Defensive - Open'),
    ('./nlp/data/vectors/Deliberate_Hasty.pt', 'Deliberate - Hasty'),
    ('./nlp/data/vectors/Determined_Indecisive.pt', 'Determined - Indecisive'),
    ('./nlp/data/vectors/Diplomatic_Blunt.pt', 'Diplomatic - Blunt'),
    ('./nlp/data/vectors/Dismissive_Receptive.pt', 'Dismissive - Receptive'),
    ('./nlp/data/vectors/Dynamic_Static.pt', 'Dynamic - Static'),
    ('./nlp/data/vectors/Ecstatic_Despairing.pt', 'Ecstatic - Despairing'),
    ('./nlp/data/vectors/Elaborate_Simple.pt', 'Elaborate - Simple'),
    ('./nlp/data/vectors/Elated_Dejected.pt', 'Elated - Dejected'),
    ('./nlp/data/vectors/Elusive_Clear.pt', 'Elusive - Clear'),
    ('./nlp/data/vectors/Empathetic_Insensitive.pt', 'Empathetic - Insensitive'),
    ('./nlp/data/vectors/Empathetic_Unsympathetic.pt', 'Empathetic - Unsympathetic'),
    ('./nlp/data/vectors/Empowered_Disempowered.pt', 'Empowered - Disempowered'),
    ('./nlp/data/vectors/Encouraging_Discouraging.pt', 'Encouraging - Discouraging'),
    ('./nlp/data/vectors/Energetic_Lethargic.pt', 'Energetic - Lethargic'),
    ('./nlp/data/vectors/Engaging_Aloof.pt', 'Engaging - Aloof'),
    ('./nlp/data/vectors/Engaging_Detached.pt', 'Engaging - Detached'),
    ('./nlp/data/vectors/Enthusiastic_Apathetic.pt', 'Enthusiastic - Apathetic'),
    ('./nlp/data/vectors/Enthusiastic_Indifferent.pt', 'Enthusiastic - Indifferent'),
    ('./nlp/data/vectors/Euphoric_Despondent.pt', 'Euphoric - Despondent'),
    ('./nlp/data/vectors/Evasive_Direct.pt', 'Evasive - Direct'),
    ('./nlp/data/vectors/Evocative_Uninspiring.pt', 'Evocative - Uninspiring'),
    ('./nlp/data/vectors/Exuberant_Gloomy.pt', 'Exuberant - Gloomy'),
    ('./nlp/data/vectors/Fierce_Submissive.pt', 'Fierce - Submissive'),
    ('./nlp/data/vectors/Flexible_Inflexible.pt', 'Flexible - Inflexible'),
    ('./nlp/data/vectors/Flippant_Serious.pt', 'Flippant - Serious'),
    ('./nlp/data/vectors/Focused_Distracted.pt', 'Focused - Distracted'),
    ('./nlp/data/vectors/Generous_Stingy.pt', 'Generous - Stingy'),
    ('./nlp/data/vectors/Genuine_Phony.pt', 'Genuine - Phony'),
    ('./nlp/data/vectors/Grateful_Ungrateful.pt', 'Grateful - Ungrateful'),
    ('./nlp/data/vectors/Honest_Deceitful.pt', 'Honest - Deceitful'),
    ('./nlp/data/vectors/Inattentive_Attentive.pt', 'Inattentive - Attentive'),
    ('./nlp/data/vectors/Indecisive_Decisive.pt', 'Indecisive - Decisive'),
    ('./nlp/data/vectors/Informative_Misleading.pt', 'Informative - Misleading'),
    ('./nlp/data/vectors/Inquisitive_Disinterested.pt', 'Inquisitive - Disinterested'),
    ('./nlp/data/vectors/Insightful_Superficial.pt', 'Insightful - Superficial'),
    ('./nlp/data/vectors/Inspired_Uninspired.pt', 'Inspired - Uninspired'),
    ('./nlp/data/vectors/Introspective_Extrospective.pt', 'Introspective - Extrospective'),
    ('./nlp/data/vectors/Joyful_Sorrowful.pt', 'Joyful - Sorrowful'),
    ('./nlp/data/vectors/Jubilant_Forlorn.pt', 'Jubilant - Forlorn'),
    ('./nlp/data/vectors/Kind_Callous.pt', 'Kind - Callous'),
    ('./nlp/data/vectors/Loyal_Disloyal.pt', 'Loyal - Disloyal'),
    ('./nlp/data/vectors/Measured_Impulsive.pt', 'Measured - Impulsive'),
    ('./nlp/data/vectors/Nonchalant_Concerned.pt', 'Nonchalant - Concerned'),
    ('./nlp/data/vectors/Optimistic_Pessimistic.pt', 'Optimistic - Pessimistic'),
    ('./nlp/data/vectors/Outgoing_Introverted.pt', 'Outgoing - Introverted'),
    ('./nlp/data/vectors/Passionate_Detached.pt', 'Passionate - Detached'),
    ('./nlp/data/vectors/Patient_Impatient.pt', 'Patient - Impatient'),
    ('./nlp/data/vectors/Perplexed_Clear.pt', 'Perplexed - Clear'),
    ('./nlp/data/vectors/Polite_Impolite.pt', 'Polite - Impolite'),
    ('./nlp/data/vectors/Polite_Rude.pt', 'Polite - Rude'),
    ('./nlp/data/vectors/Precise_Vague.pt', 'Precise - Vague'),
    ('./nlp/data/vectors/Radiant_Drab.pt', 'Radiant - Drab'),
    ('./nlp/data/vectors/Rambling_Concise.pt', 'Rambling - Concise'),
    ('./nlp/data/vectors/Reserved_Outgoing.pt', 'Reserved - Outgoing'),
    ('./nlp/data/vectors/Resilient_Fragile.pt', 'Resilient - Fragile'),
    ('./nlp/data/vectors/Respectful_Disrespectful.pt', 'Respectful - Disrespectful'),
    ('./nlp/data/vectors/Responsive_Unresponsive.pt', 'Responsive - Unresponsive'),
    ('./nlp/data/vectors/Sincere_Insincere.pt', 'Sincere - Insincere'),
    ('./nlp/data/vectors/Succinct_Rambling.pt', 'Succinct - Rambling'),
    ('./nlp/data/vectors/Supportive_Unsupportive.pt', 'Supportive - Unsupportive'),
    ('./nlp/data/vectors/Tenacious_Reluctant.pt', 'Tenacious - Reluctant'),
    ('./nlp/data/vectors/Tentative_Definite.pt', 'Tentative - Definite'),
    ('./nlp/data/vectors/Thoughtful_Impulsive.pt', 'Thoughtful - Impulsive'),
    ('./nlp/data/vectors/Thrilled_Disheartened.pt', 'Thrilled - Disheartened'),
    ('./nlp/data/vectors/Tolerant_Intolerant.pt', 'Tolerant - Intolerant'),
    ('./nlp/data/vectors/Trustworthy_Unreliable.pt', 'Trustworthy - Unreliable'),
    ('./nlp/data/vectors/Understanding_Unsympathetic.pt', 'Understanding - Unsympathetic'),
    ('./nlp/data/vectors/Unresponsive_Responsive.pt', 'Unresponsive - Responsive'),
    ('./nlp/data/vectors/Vibrant_Dull.pt', 'Vibrant - Dull'),
    ('./nlp/data/vectors/Witty_Dull.pt', 'Witty - Dull')
],
        validators=[DataRequired()],
        render_kw={'class': 'text-options-dropdown'}
    )

    submit = SubmitField('Submit')
